# Singular value Decomposition


The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler.

In [22]:
#Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("matrix A:\n",A,"\n")
# SVD
U, s, VT = svd(A)
print("matrix U:\n",U,"\n")
print("matrix s:\n",s,"\n")
print("matrix VT:\n",VT)

matrix A:
 [[1 2]
 [3 4]
 [5 6]] 

matrix U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]] 

matrix s:
 [9.52551809 0.51430058] 

matrix VT:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [23]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("Original Matrix\n",A,"\n")
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print("Reconstructed Matrix\n",B)

Original Matrix
 [[1 2]
 [3 4]
 [5 6]] 

Reconstructed Matrix
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
